---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello again !" 
      


name: Erstelle eine Datei
  file:
    path: /emp/Testdatei_Tortentante
    state: Touch
